# Generated by Django 4.1.3 on 2024-05-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviereviews',
            name='movie_name',
            field=models.CharField(default='Unknown', max_length=300),
        ),
    ]
