version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8008:8008"
    environment:
      - MONGO_URI=mongodb://mongo:27017/test
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
